# Generated by Django 3.0.7 on 2020-06-19 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField()),
                ('short_url', models.URLField(max_length=25, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
