# Generated by Django 3.0.7 on 2020-06-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.RemoveField(
            model_name='url',
            name='owner',
        ),
        migrations.AddField(
            model_name='url',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.SlugField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
